#!/usr/bin/env python3
"""Script to plot rewards generated by linear RL trader."""

from pathlib import Path

import click
from matplotlib import pyplot as plt
import numpy as np


@click.command()
@click.option(
    "--train", "-t", is_flag=True, help="Plots results from training if set otherwise testing."
)
def main(train: bool) -> None:
    rewards_dir = Path(__file__).parent / "data/linear_rl_trader_rewards"
    rewards_file = rewards_dir / ("train.npy" if train else "test.npy")
    rewards = np.load(rewards_file)

    plt.hist(rewards, bins=50)
    plt.show()


if __name__ == "__main__":
    main()
