[tool.isort]
profile = "black"
src_paths = ["exercises/"]
multi_line_output = 3
force_grid_wrap = 0
wrap_length = 100
line_length = 100
use_parentheses = true
include_trailing_comma = true
force_sort_within_sections = true
sort_relative_in_force_sorted_sections = true
lines_after_imports = 2
order_by_type = false
case_sensitive = false
reverse_relative = true
sections = ["FUTURE","STDLIB","THIRDPARTY","LOCALFOLDER"]
no_lines_before = "LOCALFOLDER"
extend_skip = ["_version.py", "versioneer.py"]
extend_skip_glob = ["docs/*", "*venv*/*"]

[tool.black]
line-length = 100
include = '(src\/.*|tests\/.*|setup.py|exercises\/.*)'
extend-exclude = '(.*\/_version.py)'

[tool.flake8]
max-line-length = 100
max-doc-length = 80
ignore = "E226,E121,E123,E126,E24,E704,E203,E122,E127,E128,W504,E731,W605,F541,E741,F821,W503"
count = true
exclude = ".git,__pycache__,docs/source/conf.py,old,build,dist,.venv"
show_source = true
statistics = true

[tool.mypy]
mypy_path = "exercises/"
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
